### ISSUE TITLE
Need help how to add  presentation data on Creat meeting

### ISSUE THREAD

**Issue by judhisahoo** [sanduhrs/php-bigbluebutton#9]
Hi,

i am fresher and  implemented basic integration.
I was change slide and presentation  in run time.

I have gone through the meeting class seen there is addSlides(Document $document).
Sorry i am fresher but unable getting how pass data for document.
Can any one help to provide some sample code to add document  while creating the meeting.

thanks.. in Advance

**Comment by sanduhrs** [comment]
The functionality is only available in the latest release.
Please see the docs: https://github.com/sanduhrs/php-bigbluebutton#add-a-meeting-with-pre-uploaded-slides
